### ISSUE TITLE
Crash Issue at the beginning of Doctor Fight

### ISSUE THREAD

**Issue by sparkst0rm** [Norbyte/ositools#30]
It says Script Extender crash and tells me to send a crash report. Not Sure where I can find the crash logs. 4e87 was the crash log dump info. 

I was able to do the fight the first time and died, reloaded the save and tried again and it keeps crashing

I reloaded a save from before it by only a few minutes, and nearly the same location and did not experience a crashing issue. I will continue to test and see what causes it to occur. Let me know what information is needed and how i could provide it

I found the source of the issue, opening his inventory before the fight so I can buy all the potions so he doesn't chug them all before the fight seems to trigger the crash

**Comment by Norbyte** [comment]
Hi,

I just got around to check your crash dump. This seems to be a base game bug, I've seen it a few times since but have been unable to determine what causes the issue.
The crash is triggered by an NPC or character being transformed (possibly because of using a potion?) without the appropriate stats being present.

**Comment by sparkst0rm** [comment]
Oh I forgot to mention how we resolved this

It was an issue with the mod “Full Loot” it must have changed the doctor’s inventory in some way on transform that causes it to bug out. When we disabled some of it’s features it ended up resolving
