### ISSUE TITLE
Client mod version doesnt match servers

### ISSUE THREAD

**Issue by TyGr10** [Norbyte/ositools#55]
A couple of friends and I downloaded the script extender and one of us gets an error as soon as they join either of the other two. The error says "Client (Player 1) mod version of Divinity: Original Sin 2 (v1.6.28.7953) doesnt match servers (v1.6.63.6551)" If we uninstall script extender this error goes away. I have done some searching and I found a reddit post with the same issues but they never found a resolution.

**Comment by Thehail** [comment]
This seems more like you or your friend have an outdated version of Divinity base game. I think you can see the version number on the main menu, i'm not sure.

**Comment by TyGr10** [comment]
We have both checked and we are using the same also we can play just fine without script extender. We may have found a solution he deleted the "Mods" folder in \steamapps\common\Divinity Original Sin 2\DefEd\Data\ and we were able to play with script extender.

**Comment by Norbyte** [comment]
In this case it was probably caused by manually extracting the .pak files to the Divinity data directory, and later the game updated to a newer version, but the extracted files take precedence over the packaged ones, so the game still loaded the old version.

It's not recommended to extract anything to the Div data directory for this reason.
