### ISSUE TITLE
Tools not working

### ISSUE THREAD

**Issue by unga02** [Norbyte/ositools#9]
The mod I'm trying to use with this tool doesn't work.
When loading a save or starting a new game a message "unable to create working story" pops up and the mod's featues aren't present.

The debug console at start shows 2 messages:
LibraryManager::FindServerGlobalsEoCApp(): Could not extract global from func @ 00007FF68FE49E90
LibraryManager::FindServerGlobalsEoCApp(): Could not extract global from func @ 00007FF68FE679D0

After loading a save i get these messages:
OsirisProxy::CompileWrapper: Starting compilation of 'C:/Users/Ugnius/Documents/Larian Studios/Divinity Original Sin 2 Definitive Edition/Temp/Story/story_generated.div'
Osiris Error: 0 error(s), 3 warning(s) in compilation.
OsirisProxy::CompileWrapper: Compilation FAILED.
OsirisProxy::OnAfterOsirisLoad: 52071 nodes
CustomFunctionInjector::OnAfterGetFunctionMappings(): No. funcs: 960
CustomFunctionInjector::OnAfterGetFunctionMappings(): No. funcs after filtering: 960
Host mod settings:
Client mod settings:

Not sure if that has to do with anything.
I've tried multiple versions of this tool with no success.

I'm running Windows 10 LTSC.
Tried it on another computer with the same OS and got identical results.

**Comment by Norbyte** [comment]
Hi,

This is a story compilation error, i.e. the scripts in one of your mods failed to build properly. It mostly happens if there are typing conflicts in the scripts.
To find out what the exact error is, create `OsirisExtenderSettings.json` in `DefEd\bin` with the following contents:
```json
{
    "CreateConsole": true,
    "LogCompile": true
}
```

It will create a compilation log file in `My Documents\OsirisLogs` which you can then inspect to find which mod is the issue.
